[package]
name = "cache"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "cache"
path = "src/main.rs"

[dependencies]
byteorder = "1.3.2"
postgres = "0.15.2"
quick-protobuf = "0.6.3"
rand = "0.6.5"
